services:
  mi-research-max-bot:
    build: .
    image: mi-research-max-bot:1.0.0
    container_name: mi-research-max-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=Europe/Moscow
      - PYTHONUNBUFFERED=1
    volumes:
      - ./config:/app/config:ro
      - ./backups:/app/backups
      - mi-research-db:/app/database
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  nginx:
    image: nginx:alpine
    container_name: mi-research-nginx
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/live/mi-research-max-bot.ru/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/mi-research-max-bot.ru/privkey.pem:/etc/ssl/private/privkey.pem:ro
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
    depends_on:
      - mi-research-max-bot

volumes:
  mi-research-db:
